"""Loads the synthetic device/telemetry/alert-scenario corpus generated by
data/generators/generate_telemetry.py into memory. Read-only — Copilot doesn't write
telemetry, only observes it (real sensor ingestion is out of scope; see docs/ROADMAP.md).
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta
from pathlib import Path

from fieldforge_contracts import DataQualityFlag, Device, DeviceType, SensorMetric, TelemetryPoint

DEFAULT_TELEMETRY_DIR = Path(__file__).resolve().parents[3] / "data" / "samples" / "telemetry"


class TelemetryStore:
    def __init__(self, telemetry_dir: Path = DEFAULT_TELEMETRY_DIR) -> None:
        self._dir = telemetry_dir
        self._devices: dict[str, Device] = {}
        self._points: dict[str, list[TelemetryPoint]] = {}
        self._alerts: list[dict] = []
        self._load()

    def _load(self) -> None:
        devices_path = self._dir / "devices.json"
        if not devices_path.exists():
            raise FileNotFoundError(
                f"{devices_path} not found — run `python data/generators/generate_telemetry.py` first"
            )
        for row in json.loads(devices_path.read_text(encoding="utf-8")):
            device = Device(
                id=row["id"],
                name=row["name"],
                device_type=DeviceType(row["device_type"]),
                site=row["site"],
            )
            self._devices[device.id] = device
            jsonl_path = self._dir / f"{device.id}.jsonl"
            points = []
            for line in jsonl_path.read_text(encoding="utf-8").splitlines():
                if not line.strip():
                    continue
                raw = json.loads(line)
                points.append(
                    TelemetryPoint(
                        device_id=raw["device_id"],
                        metric=SensorMetric(raw["metric"]),
                        value=raw["value"],
                        timestamp=raw["timestamp"],
                        quality_flag=DataQualityFlag(raw["quality_flag"]),
                    )
                )
            self._points[device.id] = points

        self._alerts = json.loads((self._dir / "alerts.json").read_text(encoding="utf-8"))

    def get_device(self, device_id: str) -> Device | None:
        return self._devices.get(device_id)

    def get_history(
        self, device_id: str, start: datetime | None = None, end: datetime | None = None
    ) -> list[TelemetryPoint]:
        points = self._points.get(device_id, [])
        if start is None and end is None:
            return list(points)

        def _in_range(p: TelemetryPoint) -> bool:
            after_start = start is None or p.timestamp >= start
            before_end = end is None or p.timestamp <= end
            return after_start and before_end

        return [p for p in points if _in_range(p)]

    def get_window(
        self, device_id: str, center: datetime, half_width_seconds: float
    ) -> list[TelemetryPoint]:
        delta = timedelta(seconds=half_width_seconds)
        return self.get_history(device_id, start=center - delta, end=center + delta)

    def list_alert_scenarios(self) -> list[dict]:
        return list(self._alerts)
